### PR TITLE
[NO JIRA] Node version update to 6.10.3 to match Lambda runtime environments

### PR DESCRIPTION
**Pull request by sandeepmjay**

### CODE REVIEW

**Comment by johncrossman** [comment]
@sandeepmjay Update README.md?

**Comment by johncrossman** [comment]
@sandeepmjay ...and `.travis.yml`?

**Comment by sandeepmjay** [comment]
@johncrossman - amends are in. Thanks for the review

**Comment by johncrossman** [comment]
Who needs Travis!

**Pull request merged**
